name: Update Issue Labels on Merge to Dev

on:
  pull_request:
    types: [closed]

jobs:
  update-issue-labels:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Update linked issue labels
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // 1. Get PR body
            const pr = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
            const prBody = pr.data.body || "";

            // 2. Find all linked issues using #123 syntax
            const issueNumbers = Array.from(prBody.matchAll(/#(\d+)/g)).map(m => parseInt(m[1]));

            if (issueNumbers.length === 0) {
              console.log("No linked issues found in PR body.");
              return;
            }

            // 3. Update each issue
            for (const issueNumber of issueNumbers) {
              console.log(`Processing issue #${issueNumber}`);

              // Get current labels
              const { data: issue } = await github.rest.issues.get({
                owner,
                repo,
                issue_number: issueNumber,
              });

              const labels = issue.labels.map(l => l.name);

              // Remove "status: in progress" if exists
              if (labels.includes("status: in progress")) {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: issueNumber,
                  name: "status: in progress",
                }).catch(err => {
                  if (err.status !== 404) throw err;
                });
              }

              // Add "status: in dev" if not already present
              if (!labels.includes("status: in dev")) {
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issueNumber,
                  labels: ["status: in dev"],
                });
              }
            }

            console.log("Finished updating labels for linked issues.");
